import os

# base dir is the one containing the config file, paths should be relative to it
BASE_PATH = os.path.dirname(os.path.abspath(__file__))

MODELS_PATH = os.path.join(BASE_PATH, 'models_dot')
RESULTS_PATH = os.path.join(BASE_PATH, 'results')

# generated by os.urandom(24) - necessary to sign client cookies so they can't forge variables
SECRET_KEY = b'I\x9c\xda\xe7\x18\x88\x91Y\xfe\x04R\xb5\xecjfO\x02\xdak\x80\x89C\x0cF'

del os